### ISSUE TITLE
走行体の使い方をドキュメント化する

### ISSUE THREAD

**Issue by arimakaoru** [KatLab-MiyazakiUniv/etrobocon2019#166]
### 完了条件
- docsディレクトリに走行体の使い方を説明したmarkdownファイルとpdfファイルがある

**Comment by sigenaga** [comment]
最新プログラムを導入して走れせてみた結果、無事動きました。とても速いが、やはり黒線が交わる所でコースアウトしてしまいました。安全性に欠けるようです。
