### ISSUE TITLE
Controllerクラスにモーター制御の関数を追加する

### ISSUE THREAD

**Issue by Tamiyas** [KatLab-MiyazakiUniv/etrobocon2019#68]
### 完了条件
- Controllerクラスにev3_set_motor_powerを呼び出すような関数が追加されている
- Controllerクラスにev3_get_motor_countsを呼び出すような関数が追加されている
- ControllerクラスのMotor型のメンバー変数がprivateになっている
- 追加した関数のテストコードが書かれている

**Comment by korosuke613** [comment]
> 追加した関数のテストコードが書かれている

Controllerクラスはテストできないけど、ダミーのControllerクラスをテストすれば良いの？

**Comment by Tamiyas** [comment]
それでいいと思うよ。
