### ISSUE TITLE
カメラと三脚の用意

### ISSUE THREAD

**Issue by Takahiro55555** [KatLab-MiyazakiUniv/etrobocon2019#79]
### 完了条件
- カメラと三脚を用意し、設置する

#### 関連資料（省略可）
https://www.dropbox.com/sh/6u2tp0cw92aotq6/AACC6-Mnfzy9svj2dxnFzw0Sa/%E9%9B%A3%E6%89%80%E7%B5%84%E7%AB%8B%E5%9B%B3?dl=0&preview=ETRC2019_nansyo_1.1.0.pdf&subfolder_nav_tracking=1

**Comment by korosuke613** [comment]
月曜日にカメラが届く予定です。
三脚は僕があげｍす・

**Comment by korosuke613** [comment]
カメラ来ました。

**Comment by korosuke613** [comment]
設置しましら
